services:
  resume:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: runtime
      no_cache: true
    env_file:
      - .env
    command:
      - yarn
      - preview
      - --host=0.0.0.0
      - --port=3000
    ports:
      - 5173:3000
    pull_policy: always
    restart: always
